<a href="https://colab.research.google.com/github/1saanya7/ml-projects-classification/blob/main/sona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import the dataset


In [ ]:
dataset = pd.read_csv('sonar.all-data.csv', header=None)
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]


In [ ]:
print(y)

['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']


In [ ]:
dataset.describe()

0       1       2       3      4       5       6       7       8   \
count      209     209     209     209    209     209     209     209     209   
unique     178     183     191     182    194     197     196     202     206   
top     0.0201  0.0394  0.0476  0.0108  0.063  0.1267  0.0771  0.0664  0.0598   
freq         5       2       2       3      2       2       3       2       2   

            9   ...      51      52      53      54      55      56      57  \
count      209  ...     209     209     209     209     209     209     209   
unique     208  ...     145     135     135     130     123     122     125   
top     0.2354  ...  0.0091  0.0129  0.0079  0.0075  0.0054  0.0037  0.0036   
freq         2  ...       5       5       5       5       5       7       6   

           58      59   60  
count     209     209  209  
unique    120     110    3  
top     0.007  0.0053    M  
freq        6       7  111  

[4 rows x 61 columns]

In [ ]:
dataset.head()

0       1       2       3       4       5       6       7       8   \
0  Freq_1  Freq_2  Freq_3  Freq_4  Freq_5  Freq_6  Freq_7  Freq_8  Freq_9   
1    0.02  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
2  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
3  0.0262  0.0582  0.1099  0.1083  0.0974   0.228  0.2431  0.3771  0.5598   
4    0.01  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   

        9   ...       51       52       53       54       55       56  \
0  Freq_10  ...  Freq_52  Freq_53  Freq_54  Freq_55  Freq_56  Freq_57   
1   0.2111  ...   0.0027   0.0065   0.0159   0.0072   0.0167    0.018   
2   0.2872  ...   0.0084   0.0089   0.0048   0.0094   0.0191    0.014   
3   0.6194  ...   0.0232   0.0166   0.0095    0.018   0.0244   0.0316   
4   0.1264  ...   0.0121   0.0036    0.015   0.0085   0.0073    0.005   

        57       58       59     60  
0  Freq_58  Freq_59  Freq_60  Label  
1   0.0084    0.009   0.0032      R  
2   0.0049   0.0052   0.0044      R  
3   0.0164   0.0095   0.0078      R  
4   0.0044    0.004   0.0117      R  

[5 rows x 61 columns]

In [ ]:
dataset.shape

(209, 61)

In [ ]:
dataset[60].value_counts()

M        111
R         97
Label      1
Name: 60, dtype: int64

In [ ]:
dataset.groupby(60).mean()

<ipython-input-28-773040ac26bb>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  dataset.groupby(60).mean()


Empty DataFrame
Columns: []
Index: [Label, M, R]

No charts were generated by quickchart


Splitting the dataset into test set and training set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.2,random_state=0)

In [ ]:
print(X_train)

[[0.0307 0.0523 0.0653 ... 0.0121 0.0124 0.0055]
 [0.0707 0.1252 0.1447 ... 0.0131 0.0154 0.0218]
 [0.0762 0.0666 0.0481 ... 0.0048 0.0107 0.0094]
 ...
 [0.0228 0.0106 0.013  ... 0.0045 0.0063 0.0039]
 [0.0373 0.0281 0.0232 ... 0.0054 0.0085 0.006 ]
 [0.018  0.0444 0.0476 ... 0.005  0.0073 0.0022]]


In [ ]:
print(X_test)

[[0.0079 0.0086 0.0055 ... 0.0058 0.0059 0.0032]
 [0.0229 0.0369 0.004  ... 0.0029 0.0104 0.0163]
 [0.0442 0.0477 0.0049 ... 0.0105 0.0059 0.0105]
 ...
 [0.0094 0.0611 0.1136 ... 0.0168 0.0245 0.0154]
 [0.0156 0.021  0.0282 ... 0.0056 0.0048 0.0024]
 [0.0099 0.0484 0.0299 ... 0.016  0.0106 0.0134]]


In [ ]:
print(y_train)

['M' 'M' 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M'
 'M' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'R' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'R'
 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M'
 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'M'
 'M' 'M' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'R' 'R'
 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R'
 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R'
 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'R'
 'M' 'M' 'R' 'M']


In [ ]:
print(y_test)

['R' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'R'
 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'M' 'M'
 'M' 'M' 'R' 'M' 'M' 'R']


training the dataset on logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

predict the value for a new input

In [ ]:
print(classifier.predict([[0.0587,	0.121	,0.1268	,0.1498	,0.1436,	0.0561,	0.0832,	0.0672,	0.1372,	0.2352,	0.3208,	0.4257,	0.5201,	0.4914,	0.595,	0.7221,	0.9039,	0.9111,	0.8723,	0.7686,	0.7326,	0.5222,	0.3097,	0.3172,	0.227	,0.164,	0.1746,	0.1835	,0.2048,	0.1674	,0.2767	,0.3104	,0.3399,	0.4441,	0.5046,	0.2814,	0.1681,	0.2633,	0.3198,	0.1933,	0.0934,	0.0443	,0.078	,0.0722	,0.0405	,0.0553	,0.1081	,0.1139	,0.0767	,0.0265	,0.0215	,0.0331	,0.0111,	0.0088	,0.0158	,0.0122	,0.0038,	0.0101,	0.0228,	0.0124]]))

['M']


predict the value for the test set

In [ ]:
y_pred  = classifier.predict(X_test)

In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[['R' 'R']
 ['M' 'R']
 ['M' 'R']
 ['R' 'R']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'R']
 ['M' 'R']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'R']]


creating confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)
accuracy_score(y_test, y_pred)

[[20  6]
 [ 1 15]]


0.8333333333333334